### ISSUE TITLE
I love this script idea, how does mount app fit in?

### ISSUE THREAD

**Issue by ghost** [canalnoises/OS9GameLauncher#2]
Hi there I love the script idea, I’m not seeing anywhere in the script for the virtual cd mount app to be utilized. Is there a place where I should have this app located for the script to use? I’m running OS 9.2.2, macOS lives image on a quick silver machine. Thank you

**Comment by canalnoises** [comment]
Hi @varainer! The script doesn't really interface with the image mounting app directly. It just tells Finder to open the ISO file, and as long as you have the mounting app installed, Finder should use it to open the file. Let me know if you have any trouble getting it to work. I'd be happy to help :)

**Comment by ghost** [comment]
Thank you for your response! I actually didn't think of mac os 9.2.2 having file association. I have iso files that are somehow tied to SimpleText. I've opened File Exchange in control panel and I'm trying to add the mounting app to the file type list. Installing the mount app didn't really give me any option to use it as an open with app.

**Comment by canalnoises** [comment]
Hmm, I don't remember how to fix that... See if you can you do something like this in the script. 

`tell application "Virtual CD/DVD-ROM Utility" to open file:path`

Unfortunately I don't have an OS 9 machine set up right now so I don't have a way to test it myself.

**Comment by ghost** [comment]
Ah so this was all unrelated but I used Creator Changer and selected an iso file, then in the app I set this info and the app now opens in virtual mount. Creator Type: VCDM and the File Type: GImg (both types are case-sensitive).
Thank you!

**Comment by canalnoises** [comment]
Ah, perfect! Nice job!
